version: "3"
services:
  web:
    build: .
    environment:
      - MONGODB_PASS=
      - PYTHONPATH=.
      - PORT=8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
